version: '3.9'

services:
  server:
    image: public.ecr.aws/y9s1f3r5/drdoid/transporter-agent:latest
    container_name: drdroid_transporter_agent
    command: ./start-server.sh
    ports:
      - 8080:8080
    environment:
      - "DRDROID_API_TOKEN=${DRDROID_API_TOKEN}"
      - "GRAFANA_HOST=${GRAFANA_HOST}"
      - "GRAFANA_API_KEY=${GRAFANA_API_KEY}"
    networks:
      - mynetwork


networks:
  mynetwork: