version: '3.9'

services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'

  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: drd-proxy-agent
    command: ./start-server.sh
    ports:
      - 8080:8080
    environment:
      - "DRDROID_API_TOKEN=${DRDROID_API_TOKEN}"
      - "GRAFANA_HOST=${GRAFANA_HOST}"
      - "GRAFANA_API_KEY=${GRAFANA_API_KEY}"
    depends_on:
      - redis
