version: '3.9'

services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'

  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: drd-proxy-agent
    command: ./start-server.sh
    ports:
      - 8080:8080
    environment:
      - "DRDROID_PROXY_API_TOKEN=<API_TOKEN>"
      - "GRAFANA_HOST=<OPTIONAL>"
      - "GRAFANA_API_KEY=<OPTIONAL>"
    depends_on:
      - redis
